name: CI

on:
  - push
  - pull_request

jobs:

  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Build dependencies
        run: nix develop --command ghc --version
      - name: Build weiss-xmonad
        run: nix build -L
      - name: Build weiss-xmonad shell
        run: nix build -L '.#devShells.x86_64-linux.default' 
